"""race model attr

Revision ID: c09060a35233
Revises: 89139edf6e19
Create Date: 2023-04-20 14:48:08.317087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09060a35233'
down_revision = '89139edf6e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_event', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('laps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('laps')
        batch_op.drop_column('length')
        batch_op.drop_column('first_event')

    # ### end Alembic commands ###
