"""added image column to driver and race

Revision ID: cf17e8cb508b
Revises: ffd885953fcb
Create Date: 2023-04-18 11:00:05.602911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf17e8cb508b'
down_revision = 'ffd885953fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_drivers')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_image', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('car_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_image', sa.String(), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fastest_time',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.alter_column('fastest_time',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('track_image')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('car_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('driver_image')

    op.create_table('_alembic_tmp_drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('car_number', sa.INTEGER(), nullable=False),
    sa.Column('team', sa.VARCHAR(), nullable=False),
    sa.Column('driver_image', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
