"""added validations for models

Revision ID: f7ce4ced11ff
Revises: cf17e8cb508b
Create Date: 2023-04-18 14:49:20.890983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ce4ced11ff'
down_revision = 'cf17e8cb508b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_drivers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('car_number', sa.INTEGER(), nullable=False),
    sa.Column('team', sa.VARCHAR(), nullable=False),
    sa.Column('driver_image', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
